package com.example.mapdungeon.model

class Topofhiragana {
    companion object {
        val hiraganaPercent: Array<Pair<Char, Int>> = arrayOf(
            Pair('あ', 106),
            Pair('い', 112),
            Pair('う', 39),
            Pair('え', 15),
            Pair('お', 122),
            Pair('か', 139),
            Pair('き', 74),
            Pair('く', 44),
            Pair('け', 6),
            Pair('こ', 65),
            Pair('さ', 63),
            Pair('し', 107),
            Pair('す', 24),
            Pair('せ', 17),
            Pair('そ', 10),
            Pair('た', 98),
            Pair('ち', 37),
            Pair('つ', 29),
            Pair('て', 11),
            Pair('と', 78),
            Pair('な', 94),
            Pair('に', 53),
            Pair('ぬ', 3),
            Pair('ね', 4),
            Pair('の', 14),
            Pair('は', 44),
            Pair('ひ', 93),
            Pair('ふ', 47),
            Pair('へ', 4),
            Pair('ほ', 13),
            Pair('ま', 35),
            Pair('み', 129),
            Pair('む', 13),
            Pair('め', 5),
            Pair('も', 20),
            Pair('や', 52),
            Pair('ゆ', 18),
            Pair('よ', 28),
            Pair('ら', 3),
            Pair('り', 8),
            Pair('る', 4),
            Pair('れ', 2),
            Pair('ろ', 2),
            Pair('わ', 19)
        )
    }
}